name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - run: git fetch --unshallow
    - run: nix-shell -p nixFlakes --run 'nix build --option experimental-features flakes\ nix-command'
